---
- name: Configure Nginx Web Server
  hosts: web
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Customize index.html
      copy:
        src: ./index.html
        dest: /var/www/html/index.html

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: true
